### ISSUE TITLE
"muleify pack src output" encounter error

### ISSUE THREAD

**Issue by luckypoem** [AlexanderElias/muleify#1]
hi.

root@AR:/usr/local/muleify-site/example# muleify pack src output

		Mule Is Packing		

(node:18923) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Error: ENOENT: no such file or directory, scandir '/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.getInstalledBinaries (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
root@AR:/usr/local/muleify-site/example# 

how to fix it?

**Comment by xeaone** [comment]
Hello there!

It looks like you are using node version 7. If you run again using node version 6 you should not have this error.

One of muleifys module depends (node-sass) is using a method that is deprecated in node version 7. tmpDir changes to tmpdir in node 7. I will contact the node-sass project and let them know.

In the mean time can you try running muleify with version 6 of node? Let me know if that fixes it or not.

**Comment by xeaone** [comment]
@luckypoem looks like there was a bug fix in node-sass that resolved this. Muleify is updated with the most recent version of node-sass now. You can check out the discussion here [Standardize on os-tmpdir](https://github.com/sass/node-sass/issues/1018#issuecomment-284444110)

`npm uninstall muleify -g`
`npm install muleify -g`

Run the re install commands and let me know if the issue persists.

**Comment by luckypoem** [comment]
hi.
still not ok.

root@AR:/usr/local/muleify-site/example# muleify pack src output

                Mule Is Packing

(node:24734) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() inst                                                                                                 ead.
Error: ENOENT: no such file or directory, scandir '/root/.nvm/versions/node/v7.4                                                                                                 .0/lib/node_modules/muleify/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.getInstalledBinaries (/root/.nvm/versions/node/v7.4.0/lib/node_mod                                                                                                 ules/muleify/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/root/.nvm/versions/node/v7.4.0/lib/node_modules/mulei                                                                                                 fy/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/n                                                                                                 ode_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/.nvm/versions/node/v7.4.0/lib/                                                                                                 node_modules/muleify/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/.nvm/versions/node/v7.4.0/lib/node_modules/muleify/                                                                                                 node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.4.0/lib/node_modules/mule                                                                                                 ify/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
root@AR:/usr/local/muleify-site/example#

**Comment by xeaone** [comment]
Did you make sure to uninstall and re-install? Update with npm does not always update the dependencies.

```
npm uninstall muleify -g
npm install muleify -g
```

What kind of OS are you using? Also I would suggest using the Node LTS which is currently version 6. If you switch to this version the issue should not persist. Most packages are built for version the LTS/6.

**Comment by luckypoem** [comment]
hi.

os: debian7. i installed nodev6.10.0,still not ok.
root@AR:/usr/local/muleify-site/example# muleify pack src output

		Mule Is Packing		

Error: ENOENT: no such file or directory, scandir '/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.10.0/lib/node_modules/muleify/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
root@AR:/usr/local/muleify-site/example#

and can u give a demo site built with muleify?

**Comment by luckypoem** [comment]
root@AR:/usr/local/muleify-site/example# cat /etc/issue.net
Debian GNU/Linux 7
root@AR:/usr/local/muleify-site/example# uname -a
Linux AR 2.6.32-042stab117.14 #1 SMP Tue Aug 30 17:12:57 MSK 2016 i686 GNU/Linux
root@AR:/usr/local/muleify-site/example#
